FROM docker:28.0.4-cli@sha256:2bccc79fc5fed23d876bf244fa5fbe78c54bf6b6145a9483604306fd797237d5 AS docker-cli
FROM ghcr.io/astral-sh/uv:0.10.9@sha256:10902f58a1606787602f303954cea099626a4adb02acbac4c69920fe9d278f82 AS uv
FROM python:3.12-bookworm@sha256:dbbe4ceb97851e2e5fa83798b239811f871cb743b259ba3563737349f6bcfaa0
COPY --from=docker-cli /usr/local/bin/docker /usr/local/bin/docker
COPY --from=docker-cli /usr/local/libexec/docker/cli-plugins /usr/local/libexec/docker/cli-plugins
COPY --from=uv /uv /usr/local/bin/uv
COPY stage2/custom-requirements.lock /tmp/requirements.lock
RUN uv pip install --system --require-hashes -r /tmp/requirements.lock
ENV PYTHONUNBUFFERED=1 LANGSMITH_TRACING=false
CMD ["sleep", "infinity"]
